import type { GadgetSettings } from "gadget-server";

export const settings: GadgetSettings = {
  type: "gadget/settings/v1",
  frameworkVersion: "v1.4.0",
  plugins: {
    connections: {
      shopify: {
        apiVersion: "2025-04",
        enabledModels: [
          "shopifyCarrierService",
          "shopifyCatalog",
          "shopifyCollect",
          "shopifyCollection",
          "shopifyDuty",
          "shopifyExchangeLineItem",
          "shopifyFile",
          "shopifyFulfillment",
          "shopifyFulfillmentEvent",
          "shopifyFulfillmentLineItem",
          "shopifyFulfillmentService",
          "shopifyInventoryItem",
          "shopifyInventoryLevel",
          "shopifyInventoryQuantity",
          "shopifyLocation",
          "shopifyOrder",
          "shopifyOrderAdjustment",
          "shopifyOrderLineItem",
          "shopifyOrderTransaction",
          "shopifyPriceList",
          "shopifyPriceListPrice",
          "shopifyProduct",
          "shopifyProductMedia",
          "shopifyProductOption",
          "shopifyProductVariant",
          "shopifyProductVariantMedia",
          "shopifyQuantityPriceBreak",
          "shopifyRefund",
          "shopifyRefundDuty",
          "shopifyRefundLineItem",
          "shopifyReturn",
          "shopifyReturnLineItem",
          "shopifyReturnShippingFee",
          "shopifyReverseDelivery",
          "shopifyReverseDeliveryLineItem",
          "shopifyReverseFulfillmentOrder",
          "shopifyReverseFulfillmentOrderDisposition",
          "shopifyReverseFulfillmentOrderLineItem",
          "shopifySellingPlan",
          "shopifySellingPlanGroup",
          "shopifySellingPlanGroupProduct",
          "shopifySellingPlanGroupProductVariant",
          "shopifyShippingLine",
        ],
        type: "partner",
        scopes: [
          "read_orders",
          "read_fulfillments",
          "read_returns",
          "read_products",
          "read_companies",
          "read_inventory",
          "read_locations",
          "read_product_listings",
          "read_shipping",
          "unauthenticated_read_product_listings",
          "unauthenticated_read_product_inventory",
        ],
      },
    },
  },
};
